Move to pnpm, update dependencies and remove unused dependencies

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -1,29 +1,59 @@
 name: Checks
 
-on: [workflow_call]
+on:
+  workflow_call:
+  push:
+    branches: [main]
+  pull_request:
+    types:
+      - opened # PR was open
+      - synchronize # PR was updated
+      - reopened # PR was closed and is now open again
+      - ready_for_review # PR was converted from draft to open
+      - converted_to_draft # PR was converted from open to draft
+
+concurrency:
+  group: checks_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
+permissions:
+  contents: read
 
 jobs:
   checks:
-    name: Run Checks
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      id-token: write
 
     steps:
       - name: Checkout
         uses: actions/checkout@v5
 
+      - name: Install pnpm
+        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
+
       - name: Setup node
         uses: actions/setup-node@v4
         with:
-          node-version-file: '.nvmrc'
+          node-version-file: .nvmrc
+          cache: pnpm
 
       - name: Install Dependencies
-        run: npm ci --ignore-scripts
+        run: pnpm install --frozen-lockfile --ignore-scripts
 
-      - name: Check Formatting
-        run: npm run check-formatting
+      - name: Format Check
+        run: pnpm format:check
+
+      - name: Typecheck
+        if: success() || failure()
+        run: pnpm typecheck
+
+      # - name: Lint Styles
+      #   if: success() || failure()
+      #   run: pnpm lint:styles
 
       - name: Lint
-        run: npm run lint
+        if: success() || failure()
+        run: pnpm lint
+
+      - name: Build Site
+        if: success() || failure()
+        run: pnpm build
